ALTER TABLE babies
  ADD COLUMN IF NOT EXISTS birth_date DATE,
  ADD COLUMN IF NOT EXISTS birth_weight_kg NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS birth_length_cm NUMERIC(5,1),
  ADD COLUMN IF NOT EXISTS sex TEXT;
